/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example;

import java.util.List;

import javax.swing.JFrame;

/**
 *
 * @author Nahda
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Fullscreen
        
        System.out.println("[MainJFrame] Constructor: initComponents complete — showing PilihKuisionerPanel");
        try {
            showPilihKuisionerPanel();
        } catch (Throwable t) {
            // Defensive: show full stack trace so caller (login) can display meaningful info
            System.err.println("[MainJFrame] Error while initializing main frame:");
            t.printStackTrace();
            javax.swing.SwingUtilities.invokeLater(() -> {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Gagal membuka jendela utama: " + t.toString() + "\nSee console for full stack trace",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            });
        }
    }

    /**
     * Method untuk mengganti isi panel
     */
    public void changePanel(javax.swing.JPanel panel) {
        PilihKuisionerPanel.removeAll();
        PilihKuisionerPanel.setLayout(new java.awt.BorderLayout());
        PilihKuisionerPanel.add(panel, java.awt.BorderLayout.CENTER);
        PilihKuisionerPanel.revalidate();
        PilihKuisionerPanel.repaint();
    }

    /**
     * Method untuk menampilkan panel pilih kuisioner
     */
    public void showPilihKuisionerPanel() {
        try {
            com.example.PilihKuisionerPanel panel = new com.example.PilihKuisionerPanel();
            changePanel(panel);
        } catch (Throwable t) {
            System.err.println("[MainJFrame] Error while creating PilihKuisionerPanel:");
            t.printStackTrace();
            throw t; // rethrow so callers also see the problem
        }
    }

    /**
     * Method untuk menampilkan form pengisian
     */
    public void showFormPengisianPanel(MataKuliah mk, com.example.PilihKuisionerPanel parentPanel) {
        FormPengisianPanel panel = new FormPengisianPanel(mk, parentPanel);
        changePanel(panel);
    }

    /**
     * Method untuk menampilkan halaman generate laporan
     */
    public void showGenerateReportPanel(List<MataKuliah> daftarMataKuliah) {
        GenerateReportPanel panel = new GenerateReportPanel(daftarMataKuliah);
        changePanel(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        PilihKuisionerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        PilihKuisionerPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("Sistem Penilaian Kinerja Dosen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(872, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PilihKuisionerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PilihKuisionerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PilihKuisionerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}